# Generated by Django 4.1.9 on 2023-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('user_email', models.EmailField(max_length=255)),
                ('reference', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('type', models.CharField(choices=[('inflow', 'inflow'), ('outflow', 'outflow')], max_length=255)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
